dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.1.0
compiler:
  solc:
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.1.0"
wallets:
  from_key: ${PRIVATE_KEY}
dotenv: .env
networks:
  default: development
  development:
    verify: False
  rinkeby:
    verify: False
  ganache:
    verify: False
